// A class is a construct that enables you to create your own custom types by grouping together variables of other types, methods and events.

    public class classes : MonoBehavior
    {
        int score = 0;
    }    
    public class MovementControls
    {
        public float speed;
        public float turnSpeed;
    }
    public class stwish
    {
       public int smallHarper = 1;
       public int bigHarper = 1;
       public int sadHarper = 20;
    }
    public class arrows
    {
        public int ironArrow = 50;
        public int steelArrow = 30;
        public int explodeArrow = 5;
    }